import React from 'react'
import { Link } from 'react-router-dom'

export default function Term() {
    return (
        <div className='pt-[75px] mb-[90px]'>
            <div className='flex justify-between w-[117px] ml-[23px]'>
                <Link className='text-[16px] font-[600] text-[#9CA3AF]' to="/">Home</Link>
                <img src='/image/right.png' className='pt-[4px] w-3' />
                <Link className='text-[16px] font-[600] text-[#116ACC]' to="/about_project">Terms</Link>
            </div>

            <div className='flex flex-col gap-[76px] mt-[47px]'>
                <p className='text-[32px] text-[#374151] leading-[36px] font-[700]'>
                    Terms & Conditions
                </p>
                <p className='font-[400] text-[18px] leading-[22px] text-[#374151]'>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mauris rhoncus aenean vel elit. At elementum eu facilisis sed odio morbi. Quam viverra orci sagittis eu. Eu mi bibendum neque egestas congue quisque egestas. Ac tortor vitae purus faucibus ornare suspendisse sed nisi lacus. Dis parturient montes nascetur ridiculus. Id diam vel quam elementum pulvinar. Sit amet dictum sit amet justo donec enim. Vestibulum morbi blandit cursus risus at ultrices mi tempus. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Ac orci phasellus egestas tellus rutrum. Elit sed vulputate mi sit amet mauris commodo quis imperdiet. Maecenas accumsan lacus vel facilisis.<br></br>
                    Nibh venenatis cras sed felis. Porttitor eget dolor morbi non arcu risus quis. Nibh cras pulvinar mattis nunc sed. Tincidunt arcu non sodales neque sodales. Mattis enim ut tellus elementum sagittis vitae et leo. Rutrum quisque non tellus orci ac auctor augue. Dictum varius duis at consectetur lorem donec. Quam id leo in vitae. Ultricies tristique nulla aliquet enim tortor at auctor. Magna etiam tempor orci eu lobortis elementum. Enim ut sem viverra aliquet. Ullamcorper sit amet risus nullam eget. Cras fermentum odio eu feugiat pretium nibh. Malesuada fames ac turpis egestas maecenas pharetra convallis. Nisl condimentum id venenatis a condimentum vitae sapien. Eget magna fermentum iaculis eu non. Eget mi proin sed libero. Risus pretium quam vulputate dignissim.<br></br>
                    Tristique nulla aliquet enim tortor at auctor urna nunc. Tortor posuere ac ut consequat. Ultricies integer quis auctor elit sed vulputate mi sit. Donec ultrices tincidunt arcu non sodales. Non pulvinar neque laoreet suspendisse. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Ut ornare lectus sit amet est placerat in egestas. A scelerisque purus semper eget duis at tellus. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Id diam maecenas ultricies mi eget. Varius sit amet mattis vulputate enim nulla aliquet porttitor. Vitae justo eget magna fermentum iaculis eu.<br></br>
                    Velit scelerisque in dictum non consectetur a erat nam. Egestas sed sed risus pretium quam vulputate. Ultrices mi tempus imperdiet nulla malesuada. Mi sit amet mauris commodo quis imperdiet massa tincidunt. Blandit massa enim nec dui. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Magna fermentum iaculis eu non diam phasellus vestibulum. Et malesuada fames ac turpis egestas. Egestas sed tempus urna et. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus aenean. At erat pellentesque adipiscing commodo. Non diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Sit amet consectetur adipiscing elit pellentesque habitant morbi.<br></br>
                    Eget nunc scelerisque viverra mauris in. Magna sit amet purus gravida quis blandit turpis. Risus commodo viverra maecenas accumsan lacus vel facilisis. Laoreet suspendisse interdum consectetur libero id faucibus nisl. Ac tincidunt vitae semper quis lectus nulla. In ante metus dictum at tempor commodo ullamcorper. Urna id volutpat lacus laoreet non curabitur gravida arcu ac. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Commodo nulla facilisi nullam vehicula ipsum a arcu. Morbi tristique senectus et netus et malesuada. Nulla facilisi nullam vehicula ipsum a arcu. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Morbi non arcu risus quis varius quam quisque id diam. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Orci nulla pellentesque dignissim enim sit amet. Bibendum neque egestas congue quisque egestas. Ipsum dolor sit amet consectetur adipiscing elit duis tristique. Erat velit scelerisque in dictum.<br></br>
                    Lacus luctus accumsan tortor posuere ac ut. Ipsum consequat nisl vel pretium lectus quam id. Odio morbi quis commodo odio aenean sed adipiscing. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Amet cursus sit amet dictum. Justo eget magna fermentum iaculis eu non. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Duis ultricies lacus sed turpis tincidunt id aliquet. Placerat in egestas erat imperdiet sed euismod nisi. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo nulla. Pulvinar mattis nunc sed blandit libero volutpat sed cras. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Habitant morbi tristique senectus et netus et. Turpis cursus in hac habitasse platea dictumst quisque. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a.
                    Amet consectetur adipiscing elit pellentesque. Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Morbi tristique senectus et netus et malesuada. In ornare quam viverra orci sagittis eu. Dolor morbi non arcu risus quis varius quam quisque id. Viverra orci sagittis eu volutpat. Tortor id aliquet lectus proin. Posuere ac ut consequat semper viverra nam libero justo. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ipsum consequat nisl vel pretium lectus quam id. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum est. Faucibus nisl tincidunt eget nullam non nisi.<br></br>
                    Vulputate enim nulla aliquet porttitor lacus luctus accumsan. Consectetur a erat nam at lectus. Id leo in vitae turpis massa sed elementum tempus. Sagittis id consectetur purus ut faucibus pulvinar elementum integer. Mi proin sed libero enim sed faucibus turpis in. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Egestas sed sed risus pretium quam. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Nec dui nunc mattis enim ut tellus elementum sagittis. Facilisi nullam vehicula ipsum a arcu cursus vitae congue mauris. Pretium quam vulputate dignissim suspendisse in est ante. Turpis in eu mi bibendum neque egestas congue quisque egestas. Tellus orci ac auctor augue mauris augue neque. Ultrices vitae auctor eu augue ut lectus arcu.
                    Et tortor consequat id porta nibh. Mattis nunc sed blandit libero volutpat. Volutpat sed cras ornare arcu dui vivamus. Blandit libero volutpat sed cras ornare arcu dui vivamus arcu. Commodo nulla facilisi nullam vehicula ipsum a arcu. Molestie a iaculis at erat pellentesque. Amet purus gravida quis blandit turpis cursus in hac habitasse. Consequat semper viverra nam libero justo. Ornare lectus sit amet est placerat in egestas erat imperdiet. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque.
                </p>
            </div>
        </div>
    )
}